[tool.poetry]
name = "financial-transaction-engine"
version = "0.1.0"
description = ""
authors = ["Serg97977 <sergeynorekyan6@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
phonenumbers = "^9.0.25"
pyjwt = "^2.11.0"
mysql = "^0.0.3"
mysql-connector-python = "^9.6.0"
python-dotenv = "^1.2.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
